# Generated by Django 5.2 on 2025-04-05 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='base.room'),
        ),
    ]
