# Generated by Django 5.2 on 2025-04-05 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_infocontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infocontent',
            name='urls',
        ),
        migrations.CreateModel(
            name='InfoContentUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('info_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='base.infocontent')),
            ],
        ),
    ]
