# Generated by Django 5.2 on 2025-04-05 08:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_infocontent_urls_infocontenturl'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infocontenturl',
            name='info_content',
        ),
        migrations.AddField(
            model_name='infocontenturl',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info_content_url_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='infocontenturl',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info_content_url', to='base.room'),
        ),
    ]
