# Generated by Django 5.2 on 2025-04-05 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_infocontenturl_info_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infocontenturl',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
