# Generated by Django 5.2 on 2025-04-20 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_infocontenturl_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='tags',
        ),
        migrations.AddField(
            model_name='room',
            name='tags',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='base.tag'),
        ),
    ]
