# Generated by Django 5.2 on 2025-04-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_room_tags_room_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='base.tag'),
        ),
    ]
