# Generated by Django 5.2 on 2025-05-03 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_codefolder_codesnippet_folder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomChatIndividual',
        ),
    ]
