# Generated by Django 5.2 on 2025-05-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterials',
            name='title',
            field=models.CharField(),
        ),
    ]
