# Generated by Django 5.2 on 2025-05-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_studymaterials_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterials',
            name='title',
            field=models.CharField(max_length=1500),
        ),
    ]
