# Generated by Django 5.2 on 2025-05-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_studymaterials_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterials',
            name='file',
            field=models.FileField(max_length=1500, upload_to='study_materials/'),
        ),
    ]
