# Generated by Django 5.2 on 2025-05-04 06:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_studymaterials_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterials',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='study_materials'),
        ),
    ]
