# Generated by Django 5.2 on 2025-05-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_studymaterials_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterials',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='study_materials/'),
        ),
        migrations.AlterField(
            model_name='studymaterials',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
