# Generated by Django 5.2 on 2025-05-04 06:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_studymaterials_file_alter_studymaterials_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studymaterials',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
