# Generated by Django 5.2.1 on 2025-05-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_studymaterials_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterials',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='studymaterials',
            name='cloudinary_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studymaterials',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='study_material/'),
        ),
    ]
